### ISSUE TITLE
Question about  *model evaluation*

### ISSUE THREAD

**Issue by shaoyuyoung** [zfj1998/SO_Title_Generation#2]
Hi,

Firstly, it is an interesting work.

However, when I was trying to repeat your experiment(i.e., CCBert), I meet some problems.

It seems strange when the program is `evaluating the model`. Here is the screenshot. `The log message stayed there for more than an hour`.Have you ever meeted this problem?

Thx in advance!

![901OGMN{ILPGD2PMWV XE76](https://user-images.githubusercontent.com/100203773/233645231-b91d4f08-6144-4960-a2ac-c037245b5d6a.png)

**Comment by shaoyuyoung** [comment]
After I debug, it seems that when evaluating, the model process every item slowly but I am sure I fully use my 4090 and CUDA utilization reached 100%. So far, I still haven't solved the problem
![image](https://user-images.githubusercontent.com/100203773/233682008-f460c289-1635-419e-9129-22e17dd13eea.png)

**Comment by zfj1998** [comment]
Sorry for the late response. But I am not really sure what the problem is and this repo has not been under maintenance for a long time. We may have further discussion through wechat maybe. Please send me your wechat id to zhangfengji@whu.edu.cn if you'd like to.

**Comment by shaoyuyoung** [comment]
The problem is solved.
Thx!
